---
- hosts: aws
  user: tcruz
  become: true
  gather_facts: no
  vars:
    app_name: tcruznamassa
    repo_url: https://user:password@github.com/tuliolucas/tcruznamassa.git
    home: /home/tcruz
  tasks:
    - name: Clone app
      git: repo={{repo_url}} dest={{home}}/{{app_name}}
    - name: Copy service tcruznamassa init script
      copy: src={{home}}/{{app_name}}/infraascode/tcruznamassa.service dest=/etc/systemd/system remote_src=true owner=root group=root
    - name: Start tcruznamassa service
      systemd:
        name: tcruznamassa.service
        daemon_reload: yes
        enabled: yes
        state: started
